### PR TITLE
`useCourtContracts`: Invalid address fix.

### LINKED ISSUE #271: `useCourtContracts()` can sometimes error with invalid addresses
See https://sentry.io/share/issue/d27410f4bc294160af00bab6169f0174/

Screen Shot 2020-04-06 at 2 53 10 PM

### PR DESCRIPTION
**Pull request by fabriziovigevani**
Closes #271 

We won't be using total ANT staked for networks that aren't mainnet.

### CODE REVIEW

File: src/hooks/useCourtContracts.js [hunk 1]
```diff
@@ -582,11 +579,11 @@ export function useTotalANTStakedPolling(timeout = 1000) {
     let cancelled = false
     let timeoutId
 
-    // Since we don't have the ANT contract address on the local environment we are skipping the stat
-    if (isLocalOrUnknownNetwork()) {
-      setError(true)
-      return
+    // We won't be using this stats other than from mainnet network
```
Comment (sohkai) [inline src/hooks/useCourtContracts.js:582]:
```suggestion
    // This stat is only relevant and shown on mainnet
```
