### PR TITLE
Dropdown fix

### LINKED ISSUE #154: Tasks: type filter is cut off
For some of the longer labels, the text is cut off on selection:

Screen Shot 2020-02-14 at 12 50 03 AM

cc @bpierre I believe this might be an aragonUI thing; I remember fixing this in the Dropdown and then it being unfixed afterwards...

### PR DESCRIPTION
**Pull request by rperez89**
this closes #154

### CODE REVIEW

File: src/components/Disputes/actions/DisputeVoting.js [hunk 1]
```diff
@@ -27,15 +27,15 @@ function DisputeVoting({ isJurorDrafted, onRequestCommit }) {
...
+          In favor of the plaintiff
         </VotingButton>
         <VotingButton
           mode="negative"
           wide
           disabled={!isJurorDrafted}
           onClick={() => onRequestCommit(VOTE_OPTION_AGAINST)}
         >
-          Against
+          Against the plaintiff
```
Comment (fabriziovigevani) [inline src/components/Disputes/actions/DisputeVoting.js]: I think this is from the previous PR? 😄

Comment (rperez89) [reply src/components/Disputes/actions/DisputeVoting.js]: haha yes seems that i created this one from the previous branch not develop hah
