### PR TITLE
Tasks: due date fix

### LINKED ISSUE #181: Tasks: due date says "today" even though it's tomorrow
E.g. if you go to https://court.aragon.org/dashboard or https://court.aragon.org/tasks today, you'll see:

Screen Shot 2020-02-18 at 3 18 05 PM

There's more than one day remaining so it's a bit odd it says "today". Given that "today" is also very subjective, I wonder if it's better to say "in the next day" until we get closer, e.g. less than 12 hours (or we use the browser's local time zone to check if the end date is actually in the same day as the person)?

------

Spec:

- If end date is in the same day (as the browser's time zone), say "today"
- If end date is the next day, say "in the next day"
- Otherwise, say "in X days"

### PR DESCRIPTION
**Pull request by rperez89**
this closes #181

### CODE REVIEW

File: src/components/Tasks/TaskStatus.js [hunk 1]
```diff
@@ -1,7 +1,21 @@
...
+    return ' Due Today'
+  }
+  if (diff === 1) {
+    return 'Due In the next day'
+  }
+  return `Due In ${diff} days`
+}
+
+const TaskStatus = React.memo(function TaskStatus({ dueDate }) {
   return (
```
[the remark this answers is not in the document]
Comment (rperez89) [reply src/components/Tasks/TaskStatus.js]: Not sure if we should use the `useNow` here since we are not showing a timer just a label, and i don't think the user will be looking this screen for hours. it's more like the user will enter to the task list take a look and go to complete some takss cc @bpierre

[the remark this answers is not in the document]
Comment (rperez89) [reply src/components/Tasks/TaskStatus.js]: pinging @bpierre

[the remark this answers is not in the document]
Comment (bpierre) [reply src/components/Tasks/TaskStatus.js]: Yes I think we could set a timeout for the next refresh instead, that would re-render in `startOfNextDay - now` every time?

File: src/components/Tasks/TaskStatus.js [hunk 2]
```diff
@@ -16,6 +16,22 @@ function getDueDayText(dueDate) {
 }
 
 const TaskStatus = React.memo(function TaskStatus({ dueDate }) {
+  const [refresh, setRefresh] = useState(false)
+
+  const now = new Date()
+  const refreshTime = dueDate - now
```
Comment (fabriziovigevani) [inline src/components/Tasks/TaskStatus.js]: Since the refreshing is relative to the remaining days we should calculate this as 

`const refreshTime = (dueDate - now) % DAY_IN_SECONDS` where `DAY_IN_SECONDS = 86400`

Comment (rperez89) [reply src/components/Tasks/TaskStatus.js]: I think that the timeout should be until local `00:00 hs` and then that number is updated

Comment (fabriziovigevani) [reply src/components/Tasks/TaskStatus.js]: Yes totally true 👍

File: src/components/Tasks/TaskStatus.js [hunk 3]
```diff
@@ -1,7 +1,37 @@
-import React from 'react'
+import React, { useEffect, useState } from 'react'
 import { textStyle, GU } from '@aragon/ui'
+import dayjs from 'dayjs'
```
Comment (sohkai) [inline src/components/Tasks/TaskStatus.js]: Wondering, should we make sure to always import `dayjs` from `lib/dayjs`? I assume only that import has the extended functionality?

File: src/components/Tasks/TaskStatus.js [hunk 4]
```diff
@@ -1,7 +1,37 @@
...
+import { datesDiff } from '../../utils/date-utils'
+
+function getDueDayText(dueDate) {
+  const diff = datesDiff(dayjs(), dayjs(dueDate))
+
+  if (diff === 0) {
+    return ' Due Today'
+  }
+  if (diff === 1) {
+    return 'Due In the next day'
```
Comment (sohkai) [inline src/components/Tasks/TaskStatus.js]:
```suggestion
    return 'Due in the next day'
```

File: src/components/Tasks/TaskStatus.js [hunk 5]
```diff
@@ -1,7 +1,37 @@
...
+  }
+  return `Due In ${diff} days`
```
Comment (sohkai) [inline src/components/Tasks/TaskStatus.js]:
```suggestion
  return `Due in ${diff} days`
```

File: src/utils/date-utils.js [hunk 6]
```diff
@@ -8,3 +8,24 @@ const KNOWN_FORMATS = {
 export function dateFormat(date, format) {
   return dayjs(date).format(KNOWN_FORMATS[format] || format)
 }
+
+export function datesDiff(startDate, endDate) {
```
Comment (sohkai) [inline src/utils/date-utils.js]: There's a somewhat easier way to get this:

```
if (endDate.diff(startDate, 'hour', true) < 24) {
  return endDate.get('date') === startDate.get('date') ? 0 : 1
}
return endDate.diff(startDate, 'day')
```

File: src/components/Tasks/TaskStatus.js (hunk 3 above)
Comment (rperez89) [reply src/components/Tasks/TaskStatus.js]: yes totally

File: src/utils/date-utils.js (hunk 6 above)
Comment (rperez89) [reply src/utils/date-utils.js]: but first we check that the startDate is the same than the endDate, if that condition is false then we check if the hours diff is less than 24 hours then is the next day and if non of the others is true we are returning the days diff

Comment (sohkai) [reply src/utils/date-utils.js]: The main reason I like the simplification is that this check:

> first we check that the startDate is the same than the endDate

is made redundant by `endDate.diff(startDate, 'hour', true) < 24`. If this is true, it already encompasses the year and month matching, and so we only need to check the day.

Comment (sohkai) [reply src/utils/date-utils.js]: Actually we've found [`isSame()`](https://day.js.org/docs/en/query/is-same) and should use that :smile:

File: src/components/Tasks/TaskStatus.js [hunk 7]
```diff
@@ -19,7 +18,11 @@ const TaskStatus = React.memo(function TaskStatus({ dueDate }) {
   const [refresh, setRefresh] = useState(false)
 
   const now = new Date()
-  const refreshTime = dueDate - now
+
+  const endofTime = dayjs()
+    .endOf('day')
+    .add(1, 'millisecond')
+  const refreshTime = endofTime - now
```
Comment (sohkai) [inline src/components/Tasks/TaskStatus.js]: Not sure on this; we might want to use `diff(now, 'millisecond')` or convert the dayjs variable into an actual Date (it might implicitly do this, but it feels better to know we're using two native Date objects than one dayjs object and one Date object).

It might also be clearer as `const startOfNextDay = dayjs().add(1, 'day').startOf('day')`

File: src/components/Tasks/TaskStatus.js [hunk 8]
```diff
@@ -11,10 +44,10 @@ function TaskStatus() {
         margin-left: ${GU * 0.7}px;
       `}
       >
-        Open: Due today
+        {`Open: ${getDueDayText(dueDate)}`}
```
Comment (sohkai) [inline src/components/Tasks/TaskStatus.js]: I think we should be able to do this:

```suggestion
        Open: {getDueDayText(dueDate)}
```
